---
title: "Assignment 6"
author: "Louis Wang"
date: "2022-11-09"
output: html_document # you can change to other output format if you want
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# 1. Continuous random variables and limit laws

## 1.1 (Q1)
\(P(U\in[a,b])=\int_a^bp_U(x)dx=\frac{1}{1-0}(b-a)=b-a\)

## 1.1 (Q2)
```{r}
set.seed(0)
n <- 1000
sample_X <- data.frame(U=runif(n)) %>%
  mutate(X=case_when(
    (0<=U)&(U<0.25)~3,
    (0.25<=U)&(U<0.5)~10,
    (0.5<=U)&(U<=1)~0)) %>%
  pull(X)
```


## 1.1 (Q3)
```{r}
sample_X_0310 <- function(alpha, beta, n){
  set.seed(1)
  sample_0310 <- data.frame(U=runif(n)) %>%
    mutate(X=case_when(
      (0<=U)&(U<alpha)~3,
      (alpha<=U)&(U<alpha+beta)~10,
      (alpha+beta<=U)&(U<=1)~0
    )) %>%
    pull(X)
  return (sample_0310)
}
sample_X_0310(0.25,0.25,10)
```

## 1.1 (Q4)
```{r}
sample4 <- sample_X_0310(0.5,0.1,10000)
mean(sample4)
```
The sample average is so close to the theoretical value of E(X)=2.5, since the sample size is large enough to reach the theroretical value.

## 1.1 (Q5)
```{r}
var(sample4)
```
The population variance Var(X)=8.25

## 1.1 (Q6)
```{r}
sample_0310 <- function(x){
  return (sample_X_0310(0.1, x, 100))
}
sample_mean <- function(x){
  return (mean(x))
}
sample_exceptation <- function(x){
  return (3*0.1+10*x)
}
beta = seq(0, 0.9, 0.01)
sample_x <- map(beta, sample_0310)
samples <- data.frame(beta) %>%
  mutate(sample_X = sample_x) %>%
  mutate(samplemean = map_dbl(sample_X, sample_mean)) %>%
  mutate(Expectation = map_dbl(beta, sample_exceptation))
```

## 1.1 (Q7)
```{r}
samples %>% pivot_longer(cols=c("samplemean","Expectation"),
                         names_to="name", values_to="value") %>%
  ggplot(aes(beta, value)) +
  geom_point(aes(color=name))
```


## 1.3 (Q1)

....


# 2. Location estimators with Gaussian data


## 2 (Q1)

....


## 2 (Q2)

....

# 3. (**) The law of large numbers and Hoeffding’s inequality

## 3 (Q1)





