---
title: "Assignment 5"
author: "Louis Wang"
date: "2022-10-26"
output: html_document # you can change to other output format if you want
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# 1. Conditional probability, Bayes rule and independence

## 1.1 (Q1)
\(P(B|A^c)=1-P(B^c|A^c)=1-0.75=0.25\)  
\(P(B)=P(B|A)P(A)+P(B|A^c)P(A^c)=0.8*0.9+0.25*0.1=0.745\)
\(P(A|B)=\frac{P(B|A)P(A)}{P(B)}=\frac{0.8*0.9}{0.745}=0.96644295\)

## 1.2 (Q1)
1. \(P(A|B)=\frac{P(A)}{P(B)}; when\ P(B\backslash A)=0,\ P(A|B)=1\)
2. \(PA|B)=0;\ P(A|B)=0\)
3. \(P(A|B)=\frac{P(A \bigcap B)}{P(B)}=\frac{P(B)}{P(B)}=1;\ P(A|B)=1\)
4. \(P(A|\Omega)=\frac{P(A \bigcap \Omega)}{P(\Omega)}=\frac{P(A)}{P(\Omega)}=P(A)\)
5. \(P(A \bigcap B \bigcap C)=P(A|(B \bigcap C))P(B \bigcap C)=P(A|(B \bigcap C))P(B|C)P(C)\)
6. \(P(A|B \bigcap C)=\frac{P(A \bigcap B \bigcap C)}{P(B \bigcap C)}=\frac{P(B|(A \bigcap C))P(A|C)P(C)}{P(B|C)P(C)}=\frac{P(B|(A \bigcap C))P(A|C)}{P(B|C)}\)

## 1.2 (Q2)
Suppose A = windy, B = the flight being cancelled, so
\(P(B|A)=0.3,\ P(B|A^c)=0.1,\ P(A)=0.2\)  
\(P(B^c)=1-P(B)=1-(P(B \bigcap A)+P(B \bigcap A^c))=1-(P(B|A)P(A)+P(B|A^c)P(A^c))=1-(0.3*0.2+0.1*0.8)=0.86\)

## 1.3 (Q1)
\(P(A \bigcap B \bigcap C)=P(\emptyset)=0\neq P(A)P(B)P(C)\)
so, events A,B,C are not mutually independent

## 1.4 (Q1)
\(P(B1\bigcap C2)=\frac{1}{3}(\frac{1}{3}*\frac{1}{2} + \frac{1}{3})=\frac{1}{6}\)  
\(P(A3|B1\bigcap C2)=\frac{P(A3\bigcap B1\bigcap C2)}{P(B1\bigcap C2)}=\frac{2}{3}\)  
Since the possibility of initially choose a goat is 2/3, so the possibility of winning a car if we switch the choice is 2/3, while the possibility of we don't switch the choice is 1/3, which means if we change our initial choice, the chance of winning a car is higher than we don't change.
....

# 2. Random variables and discrete random variables

## 2.1 (Q1)
When X and Y are independent, E(XY)=E(X)E(Y). So \(COV(X,Y)=E[(X-E(X)(Y-E(Y)))]=E(XY)-E(X)(Y)=0\)

## 2.2 (Q1)
1. $$p_x(X)=\begin{cases}
1-\alpha-\beta, & X=0\\
\alpha, & X=3\\
\beta, & X=10\\
0, & other\ values\\
\end{cases}$$
2. \(E(X)=3\alpha+10\beta\)
3. \(Var(X)=9\alpha+100\beta-9\alpha^2-60\alpha\beta-100\beta^2\)
4. \(SD(X)=\sqrt{9\alpha+100\beta-9\alpha^2-60\alpha\beta-100\beta^2}\)

## 2.2 (Q2)
1. \(P_X(X)=(1-\alpha-\beta)1_S(0)+\alpha1_S(3)+\beta1_S(10)\)
2. $$F_X(X)=\begin{cases}
0 & X<0\\
1-\alpha-\beta & 0\leq X<3\\
1-\beta & 3\leq X<10\\
1 & X\geq 10\\
\end{cases}$$
.....



